### ISSUE TITLE
Swift 4 Support Anytime Soon?

### ISSUE THREAD

**Issue by ndduong97** [andreamazz/AMPopTip#124]

**Comment by andreamazz** [comment]
Yeah, I hope to work on it this week.

**Comment by andreamazz** [comment]
Done, `master` is now 4.0, legacy support on branch `swift3`. Version `3.0.0` is Swift 4.

**Comment by ndduong97** [comment]
I just updated mine to version 3.0.0, but I am still getting this error: 

`Type 'NSAttributedStringKey' (aka 'NSString') has no member 'font'`

Any idea what's going on?

**Comment by andreamazz** [comment]
Is the pod compiling with swift 4?

**Comment by ndduong97** [comment]
The pod was installed successfully but the updated workspace cannot compile because of those 3 errors

**Comment by andreamazz** [comment]
Check the Pods project, select the poptip framework from the target, in the build config check if it’s building it with swift4. From the error it looks like it’s compiling with swift 3

**Comment by ndduong97** [comment]
Yeah I just checked. It's not building in swift 4

**Comment by andreamazz** [comment]
Funny, I had the inverse issue, I have a swift 4 project and swift 3 pods to integrate.
I ended up using a post install script, you can do the same for the time being.
In any case, try to update your cocoapods gem and run `pod install` again.

```ruby
swift4pods = ['AMPopTip']

post_install do |installer|
  installer.pods_project.targets.each do |target|
    if swift4pods.include? target.name
      target.build_configurations.each do |config|
        config.build_settings['SWIFT_VERSION'] = '4.0'
      end
    end
  end
end
```
